services:
  - type: web
    name: saas-ecommerce
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        value: base64:J1JY/4AmjM64GnlxDChrKiBVU57583gDrrpUJnFYj9k=
      - key: APP_NAME
        value: SaaSEcommerce
      - key: APP_URL
        value: https://saas-ecommerce-xx7e.onrender.com
      - key: CENTRAL_DOMAINS
        value: saas-ecommerce-xx7e.onrender.com,localhost,127.0.0.1
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: prefer
      - key: LOG_LEVEL
        value: debug
